version: "3"

services:
  webapp:
    # 本地构建
    # build: .
    # 远程构建
    image: ghcr.io/zerxz/youchatproxy:latest
    ports:
      - "8080:8080"
    volumes:
      - config.js:app/config.js
      - config.mjs:app/config.mjs
      - you.config.json:app/you.config.json
      - perplexityConfig.mjs:app/perplexityConfig.mjs
      - perplexityConfig.js:app/perplexityConfig.js
    env_file:
      - .env